FROM python:${PYTHON_VERSION}-alpine${ALPINE_VERSION}
ARG grpcio_version

RUN apk add g++ linux-headers

RUN apk add g++ linux-headers && \
    echo 'manylinux1_compatible = True' > /usr/local/lib/python${PYTHON_VERSION}/site-packages/_manylinux.py && \
		pip3 install --no-cache-dir grpcio==$grpcio_version

